---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-nodejs-simple-test
    trigger: true
  - put: nodejs_simple_test_image_build
    params:
      build: git-nodejs-simple-test

resources:
- name: git-nodejs-simple-test
  type: git
  source:
    uri: git@github.com:gregorycox/nodejs_simple_test.git
    branch: develop
    private_key: {{private-repo-key}}
    username: {{repo-username}}

- name: nodejs_simple_test_image_build
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: gregorycox/nodejs_simple_test_build
