---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-nodejs-simple-test
    trigger: true
  - put: docker-image
    params:
      build: git-nodejs-simple-test

resources:
- name: git-nodejs-simple-test
  type: git
  source:
    uri: https://github.com/gregorycox/nodejs_simple_test.git
    branch: develop

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-concourse-go-image}}

