---
resources:
- name: git-nodejs-simple-test
  type: git
  source:
    uri: git@github.com:gregorycox/nodejs_simple_test.git
    branch: develop
    private_key: {{private-repo-key}}
    username: {{repo-username}}

- name: nodejs_simple_test_image_build
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: gregorycox/nodejs_simple_test_build



jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-nodejs-simple-test
    trigger: true
  - put: nodejs_simple_test_image_build
    params:
      build: git-nodejs-simple-test

- name: test-docker-image
  plan:
  - get: nodejs_simple_test_image_build
    passed: [build-docker-image]
    trigger: true
  - get: git-nodejs-simple-test
    passed: [build-docker-image]
  - task: test-docker-image
    image: nodejs_simple_test_image_build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: gregorycox/nodejs_simple_test_build}
      run:
        path: /usr/src/app/node_modules/mocha/bin/mocha


